rules = [OrganizeImports]

OrganizeImports {
  blankLines = Auto
  expandRelative = true
  groupedImports = AggressiveMerge
  removeUnused = false
  groups = [
    "re:javax?\\."
    "scala."
    "zio."
    "*"
  ]
}
