version = 3.9.4
runner.dialect = scala213source3
maxColumn = 100
align.preset = more
align.multiline = true
danglingParentheses.preset = true
trailingCommas = always
rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers]
docstrings.style = Asterisk
docstrings.wrap = no
