addSbtPlugin("org.scalameta"  % "sbt-scalafmt"    % "2.5.2")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"    % "0.12.1")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"   % "2.4.1")
addSbtPlugin("com.typesafe"   % "sbt-mima-plugin" % "1.1.4")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"    % "3.12.2")
addSbtPlugin("com.github.sbt" % "sbt-pgp"         % "2.2.1")
