package zoi.pool

import java.sql.{
  Array => SqlArray,
  Blob,
  CallableStatement,
  Clob,
  Connection,
  DatabaseMetaData,
  NClob,
  PreparedStatement,
  SQLException,
  SQLWarning,
  SQLXML,
  Savepoint,
  ShardingKey,
  Statement,
  Struct,
}
import java.util.Properties
import java.util.concurrent.Executor

import scala.collection.mutable

/**
 * What a borrower holds: the physical connection with `close` rerouted to the
 * pool, the statements it opened tracked so they are closed on return, the
 * connection-state mutations recorded so a clean borrow needs no reset, and the
 * failures it raises classified so a broken connection is not pooled again.
 *
 * Statements are handed out unwrapped, so a query costs exactly what it costs
 * without a pool.
 */
private[pool] final class ConnectionHandle(
  private[pool] val pooled: PooledConnection,
  release: ConnectionHandle => Unit,
  onFailure: SQLException => Unit,
) extends Connection {

  private var opened: mutable.ArrayBuffer[Statement] = null
  @volatile private var closed                       = false
  private var released                               = false

  private def raw: Connection = {
    if (closed) throw new SQLException("connection is closed", PoolException.ConnectionDoesNotExist)
    pooled.raw
  }

  private def guarded[T](thunk: => T): T =
    try thunk
    catch {
      case failure: SQLException =>
        onFailure(failure)
        throw failure
    }

  /** Most borrows open no statement, so the list is built only if one is. */
  private def track[S <: Statement](statement: S): S = {
    synchronized {
      if (opened == null) opened = mutable.ArrayBuffer.empty[Statement]
      opened += statement
    }
    statement
  }

  private def dirty(): Unit = pooled.stateDirty = true

  /** Wins the right to return this connection exactly once. */
  private[pool] def claimRelease(): Boolean =
    synchronized {
      if (released) false
      else {
        released = true
        closed = true
        true
      }
    }

  /** Closes what the borrower opened; errors here never mask the borrow. */
  private[pool] def closeTrackedStatements(): Unit = {
    val statements = synchronized {
      val snapshot = opened
      opened = null
      snapshot
    }
    if (statements != null)
      statements.foreach { statement =>
        try statement.close()
        catch { case _: SQLException => () }
      }
  }

  override def close(): Unit = if (!closed) release(this)

  override def isClosed: Boolean = closed || pooled.raw.isClosed

  private[pool] def active: Boolean = !closed

  override def createStatement(): Statement = track(guarded(raw.createStatement()))

  override def createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement =
    track(guarded(raw.createStatement(resultSetType, resultSetConcurrency)))

  override def createStatement(
    resultSetType: Int,
    resultSetConcurrency: Int,
    resultSetHoldability: Int,
  ): Statement =
    track(guarded(raw.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability)))

  override def prepareStatement(sql: String): PreparedStatement =
    if (pooled.statementCache.isEmpty) track(guarded(raw.prepareStatement(sql)))
    else {
      val _ = raw
      guarded(pooled.prepare(sql))
    }

  override def prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement =
    track(guarded(raw.prepareStatement(sql, autoGeneratedKeys)))

  override def prepareStatement(sql: String, columnIndexes: scala.Array[Int]): PreparedStatement =
    track(guarded(raw.prepareStatement(sql, columnIndexes)))

  override def prepareStatement(sql: String, columnNames: scala.Array[String]): PreparedStatement =
    track(guarded(raw.prepareStatement(sql, columnNames)))

  override def prepareStatement(
    sql: String,
    resultSetType: Int,
    resultSetConcurrency: Int,
  ): PreparedStatement =
    track(guarded(raw.prepareStatement(sql, resultSetType, resultSetConcurrency)))

  override def prepareStatement(
    sql: String,
    resultSetType: Int,
    resultSetConcurrency: Int,
    resultSetHoldability: Int,
  ): PreparedStatement =
    track(
      guarded(raw.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability)),
    )

  override def prepareCall(sql: String): CallableStatement = track(guarded(raw.prepareCall(sql)))

  override def prepareCall(
    sql: String,
    resultSetType: Int,
    resultSetConcurrency: Int,
  ): CallableStatement = track(guarded(raw.prepareCall(sql, resultSetType, resultSetConcurrency)))

  override def prepareCall(
    sql: String,
    resultSetType: Int,
    resultSetConcurrency: Int,
    resultSetHoldability: Int,
  ): CallableStatement =
    track(guarded(raw.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability)))

  override def nativeSQL(sql: String): String = guarded(raw.nativeSQL(sql))

  override def setAutoCommit(autoCommit: Boolean): Unit = {
    dirty()
    guarded(raw.setAutoCommit(autoCommit))
  }

  override def getAutoCommit: Boolean = guarded(raw.getAutoCommit)

  override def commit(): Unit = guarded(raw.commit())

  override def rollback(): Unit = guarded(raw.rollback())

  override def rollback(savepoint: Savepoint): Unit = guarded(raw.rollback(savepoint))

  override def getMetaData: DatabaseMetaData = guarded(raw.getMetaData)

  override def setReadOnly(readOnly: Boolean): Unit = {
    dirty()
    guarded(raw.setReadOnly(readOnly))
  }

  override def isReadOnly: Boolean = guarded(raw.isReadOnly)

  override def setCatalog(catalog: String): Unit = {
    dirty()
    guarded(raw.setCatalog(catalog))
  }

  override def getCatalog: String = guarded(raw.getCatalog)

  override def setTransactionIsolation(level: Int): Unit = {
    dirty()
    guarded(raw.setTransactionIsolation(level))
  }

  override def getTransactionIsolation: Int = guarded(raw.getTransactionIsolation)

  override def getWarnings: SQLWarning = raw.getWarnings

  override def clearWarnings(): Unit = raw.clearWarnings()

  override def getTypeMap: java.util.Map[String, Class[_]] = raw.getTypeMap

  override def setTypeMap(map: java.util.Map[String, Class[_]]): Unit = {
    dirty()
    raw.setTypeMap(map)
  }

  override def setHoldability(holdability: Int): Unit = {
    dirty()
    raw.setHoldability(holdability)
  }

  override def getHoldability: Int = raw.getHoldability

  override def setSavepoint(): Savepoint = guarded(raw.setSavepoint())

  override def setSavepoint(name: String): Savepoint = guarded(raw.setSavepoint(name))

  override def releaseSavepoint(savepoint: Savepoint): Unit = guarded(raw.releaseSavepoint(savepoint))

  override def createClob(): Clob = raw.createClob()

  override def createBlob(): Blob = raw.createBlob()

  override def createNClob(): NClob = raw.createNClob()

  override def createSQLXML(): SQLXML = raw.createSQLXML()

  override def isValid(timeout: Int): Boolean = !closed && pooled.raw.isValid(timeout)

  override def setClientInfo(name: String, value: String): Unit = {
    dirty()
    pooled.raw.setClientInfo(name, value)
  }

  override def setClientInfo(properties: Properties): Unit = {
    dirty()
    pooled.raw.setClientInfo(properties)
  }

  override def getClientInfo(name: String): String = raw.getClientInfo(name)

  override def getClientInfo: Properties = raw.getClientInfo

  override def createArrayOf(typeName: String, elements: scala.Array[AnyRef]): SqlArray =
    raw.createArrayOf(typeName, elements)

  override def createStruct(typeName: String, attributes: scala.Array[AnyRef]): Struct =
    raw.createStruct(typeName, attributes)

  override def setSchema(schema: String): Unit = {
    dirty()
    guarded(raw.setSchema(schema))
  }

  override def getSchema: String = guarded(raw.getSchema)

  override def abort(executor: Executor): Unit = raw.abort(executor)

  override def setNetworkTimeout(executor: Executor, milliseconds: Int): Unit =
    raw.setNetworkTimeout(executor, milliseconds)

  override def getNetworkTimeout: Int = raw.getNetworkTimeout

  override def beginRequest(): Unit = raw.beginRequest()

  override def endRequest(): Unit = raw.endRequest()

  override def setShardingKeyIfValid(
    shardingKey: ShardingKey,
    superShardingKey: ShardingKey,
    timeout: Int,
  ): Boolean = raw.setShardingKeyIfValid(shardingKey, superShardingKey, timeout)

  override def setShardingKeyIfValid(shardingKey: ShardingKey, timeout: Int): Boolean =
    raw.setShardingKeyIfValid(shardingKey, timeout)

  override def setShardingKey(shardingKey: ShardingKey, superShardingKey: ShardingKey): Unit =
    raw.setShardingKey(shardingKey, superShardingKey)

  override def setShardingKey(shardingKey: ShardingKey): Unit = raw.setShardingKey(shardingKey)

  override def unwrap[T](iface: Class[T]): T =
    if (iface.isInstance(pooled.raw)) iface.cast(pooled.raw) else pooled.raw.unwrap(iface)

  override def isWrapperFor(iface: Class[_]): Boolean =
    iface.isInstance(pooled.raw) || pooled.raw.isWrapperFor(iface)
}
